language: python
sudo: false

git:
  submodules: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - dist: xenial
      python: 3.7
    - os: osx
      language: generic
      env: PYTHON_VERSION=3

addons:
  apt:
    packages:
    - ttf-dejavu

before_install:
  # As setup.py doesn't use pip, setuptools is not updated before installing dependencies
  - python$PYTHON_VERSION install --upgrade setuptools

  # Pango 1.38+ is needed to make @font-face work, remove these two lines when it's available on Travis
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p ~/.fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew pin numpy gdal postgis; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install font-dejavu-sans; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo pango gdk-pixbuf libffi; fi

script:
  - python$PYTHON_VERSION setup.py test
