# Site settings
title: WeasyPrint
email: contact@courtbouillon.org
description: The Awesome Document Factory
baseurl: ""
url: "http://weasyprint.org"
gems:
 - jekyll-redirect-from
 - jekyll-github-metadata
repository: Kozea/WeasyPrint
