name: WeasyPrint
description: Converts HTML + CSS to PDF
license: BSD
public: true
url: http://www.weasyprint.org/

menu:
  - Overview:
      link: /
  - News:
      link: /news/
  - Download:
      link: /install/
  - Documentation:
      link: /using/
  - Community:
      link: /community/

project (git):
  url: git://github.com/Kozea/WeasyPrint.git
  path: weasyprint

vcs (git):
  url: git://github.com/Kozea/WeasyPrint.git
  path: /var/db/git/weasyprint.git

code browser (github):
  project name: Kozea/WeasyPrint

bug tracker (redmine):
  base url: http://redmine.kozea.fr/
  project name: weasyprint

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: WeasyPrint
