name: WeasyPrint's tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y && sudo apt-get install ttf-dejavu -y
          mkdir -p ~/.fonts
          wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf
      - if: matrix.os == 'macos-latest'
        run: |
          brew tap homebrew/cask-fonts
          brew cask install font-dejavu-sans
          brew install cairo pango gdk-pixbuf libffi
      - if: matrix.os == 'windows-latest'
        run: |
          export "PATH=$PATH;C:\msys64\mingw64\bin"
          choco install -y python dejavufonts
          wget "http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20180531.tar.xz"
          7z e msys2-base-x86_64-20180531.tar.xz
          7z x -y msys2-base-x86_64-20180531.tar -oc:\\
          powershell "C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'"
      - run: python -m pip install --upgrade pip setuptools
      - if: matrix.os == 'windows-latest'
        run: python -m pip install --upgrade cffi
      - run: python setup.py test
