name: WeasyPrint's tests
on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y && sudo apt-get install ttf-dejavu -y
          mkdir -p ~/.fonts
          wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf
      - if: matrix.os == 'macos-latest'
        run: |
          brew tap homebrew/cask-fonts
          brew cask install font-dejavu-sans
          brew install cairo pango gdk-pixbuf libffi
      - if: matrix.os == 'windows-latest'
        run: |
          choco install -y --no-progress msys2 python dejavufonts
          powershell "C:\tool\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'"
      - run: python -m pip install --upgrade pip setuptools
      - if: matrix.os == 'windows-latest'
        run: python -m pip install --upgrade cffi
      - run: python setup.py test
